# Generated by Django 5.2.4 on 2025-07-26 21:08

import conversions.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_format', models.CharField(max_length=10)),
                ('output_format', models.CharField(max_length=10)),
                ('input_size', models.BigIntegerField()),
                ('output_size', models.BigIntegerField(blank=True, null=True)),
                ('conversion_time', models.FloatField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Conversion Histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ConversionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_file', models.FileField(upload_to='temp_uploads/')),
                ('input_filename', models.CharField(max_length=255)),
                ('input_format', models.CharField(max_length=10)),
                ('input_size', models.BigIntegerField()),
                ('output_format', models.CharField(choices=[('mp4', 'MP4 Video'), ('avi', 'AVI Video'), ('mkv', 'MKV Video'), ('mov', 'MOV Video'), ('webm', 'WebM Video'), ('mp3', 'MP3 Audio'), ('wav', 'WAV Audio'), ('flac', 'FLAC Audio'), ('aac', 'AAC Audio'), ('ogg', 'OGG Audio'), ('m4a', 'M4A Audio')], max_length=10)),
                ('output_quality', models.CharField(choices=[('144p', '144p'), ('240p', '240p'), ('360p', '360p'), ('480p', '480p'), ('720p', '720p'), ('1080p', '1080p'), ('1440p', '1440p'), ('2160p', '2160p (4K)'), ('original', 'Original Quality')], default='original', max_length=10)),
                ('custom_settings', models.JSONField(blank=True, default=dict)),
                ('output_file', models.FileField(blank=True, null=True, upload_to=conversions.models.upload_to_conversions)),
                ('output_filename', models.CharField(blank=True, max_length=255)),
                ('output_size', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('conversion_time', models.FloatField(blank=True, null=True)),
                ('compression_ratio', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
